spring:
  application:
    name: spring-kotlin-course
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_kotlin_course?useTimezone=true&serverTimezone=UTC
    username: root
    password: minha_senha
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
